spring:
  application:
    name: You don't know Hibernate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/issue_tracker
    username: admin
    password: '&ZjWlGXYkU6cATGwf5iy'
