# We don't use a JTA transaction manager in these sample apps (single datasource, local/dev).
# Explicitly tell Hibernate to disable JTA integration to avoid the warning:
# HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
